# Change these first
owner: picchiosat # Your GitHub username
repo: HBLink-Uptime # Your Github repository name

# Add your sites here
sites:
  - name: National MP Node
    url: http://dashboard.hblink.it
  - name: YSF REF
    url: https://ysf.freedmr.it
  - name: NXDN REF
    url: https://nxdn.hblink.it
  - name: P25 REF
    url: https://p25.hblink.it
  - name: M17 REF
    url: https://m17ita.hblink.it
  - name: XLX965
    url: https://xlx965.hblink.it
  - name: FreeDMR IT Bridge
    url: https://dashboard.freedmr.it
  - name: FreeDMR IT Hotspots
    url: https://hotspot.freedmr.it
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.hblink.it
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://www.hblink.it/hblink/images/HBlink.png
  name: Upptime HBLink
  introTitle: HBLink ITALIA Network Status
  introMessage: Statistiche in **real time** dei server HBLink.it 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
